/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RequisicoesRouteImport } from './routes/requisicoes'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as EmprestimosRouteImport } from './routes/emprestimos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequisicoesIdRouteImport } from './routes/requisicoes_.$id'
import { Route as InventarioIdRouteImport } from './routes/inventario_.$id'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisicoesRoute = RequisicoesRouteImport.update({
  id: '/requisicoes',
  path: '/requisicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprestimosRoute = EmprestimosRouteImport.update({
  id: '/emprestimos',
  path: '/emprestimos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisicoesIdRoute = RequisicoesIdRouteImport.update({
  id: '/requisicoes_/$id',
  path: '/requisicoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioIdRoute = InventarioIdRouteImport.update({
  id: '/inventario_/$id',
  path: '/inventario/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emprestimos': typeof EmprestimosRoute
  '/entradas': typeof EntradasRoute
  '/inventario': typeof InventarioRoute
  '/mapa': typeof MapaRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/produtos': typeof ProdutosRoute
  '/relatorio': typeof RelatorioRoute
  '/requisicoes': typeof RequisicoesRoute
  '/scan': typeof ScanRoute
  '/usuarios': typeof UsuariosRoute
  '/inventario/$id': typeof InventarioIdRoute
  '/requisicoes/$id': typeof RequisicoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emprestimos': typeof EmprestimosRoute
  '/entradas': typeof EntradasRoute
  '/inventario': typeof InventarioRoute
  '/mapa': typeof MapaRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/produtos': typeof ProdutosRoute
  '/relatorio': typeof RelatorioRoute
  '/requisicoes': typeof RequisicoesRoute
  '/scan': typeof ScanRoute
  '/usuarios': typeof UsuariosRoute
  '/inventario/$id': typeof InventarioIdRoute
  '/requisicoes/$id': typeof RequisicoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emprestimos': typeof EmprestimosRoute
  '/entradas': typeof EntradasRoute
  '/inventario': typeof InventarioRoute
  '/mapa': typeof MapaRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/produtos': typeof ProdutosRoute
  '/relatorio': typeof RelatorioRoute
  '/requisicoes': typeof RequisicoesRoute
  '/scan': typeof ScanRoute
  '/usuarios': typeof UsuariosRoute
  '/inventario_/$id': typeof InventarioIdRoute
  '/requisicoes_/$id': typeof RequisicoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/emprestimos'
    | '/entradas'
    | '/inventario'
    | '/mapa'
    | '/movimentacoes'
    | '/produtos'
    | '/relatorio'
    | '/requisicoes'
    | '/scan'
    | '/usuarios'
    | '/inventario/$id'
    | '/requisicoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/emprestimos'
    | '/entradas'
    | '/inventario'
    | '/mapa'
    | '/movimentacoes'
    | '/produtos'
    | '/relatorio'
    | '/requisicoes'
    | '/scan'
    | '/usuarios'
    | '/inventario/$id'
    | '/requisicoes/$id'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/emprestimos'
    | '/entradas'
    | '/inventario'
    | '/mapa'
    | '/movimentacoes'
    | '/produtos'
    | '/relatorio'
    | '/requisicoes'
    | '/scan'
    | '/usuarios'
    | '/inventario_/$id'
    | '/requisicoes_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmprestimosRoute: typeof EmprestimosRoute
  EntradasRoute: typeof EntradasRoute
  InventarioRoute: typeof InventarioRoute
  MapaRoute: typeof MapaRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatorioRoute: typeof RelatorioRoute
  RequisicoesRoute: typeof RequisicoesRoute
  ScanRoute: typeof ScanRoute
  UsuariosRoute: typeof UsuariosRoute
  InventarioIdRoute: typeof InventarioIdRoute
  RequisicoesIdRoute: typeof RequisicoesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisicoes': {
      id: '/requisicoes'
      path: '/requisicoes'
      fullPath: '/requisicoes'
      preLoaderRoute: typeof RequisicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprestimos': {
      id: '/emprestimos'
      path: '/emprestimos'
      fullPath: '/emprestimos'
      preLoaderRoute: typeof EmprestimosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisicoes_/$id': {
      id: '/requisicoes_/$id'
      path: '/requisicoes/$id'
      fullPath: '/requisicoes/$id'
      preLoaderRoute: typeof RequisicoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario_/$id': {
      id: '/inventario_/$id'
      path: '/inventario/$id'
      fullPath: '/inventario/$id'
      preLoaderRoute: typeof InventarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmprestimosRoute: EmprestimosRoute,
  EntradasRoute: EntradasRoute,
  InventarioRoute: InventarioRoute,
  MapaRoute: MapaRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  ProdutosRoute: ProdutosRoute,
  RelatorioRoute: RelatorioRoute,
  RequisicoesRoute: RequisicoesRoute,
  ScanRoute: ScanRoute,
  UsuariosRoute: UsuariosRoute,
  InventarioIdRoute: InventarioIdRoute,
  RequisicoesIdRoute: RequisicoesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
